package com.example.api.setup.func;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class testdataobject implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public testdataobject() {
    }




}